#! /usr/bin/env/python3




import lxml
import fileinput



from xml.etree import ElementTree as et


def internationalize_svg(fic):
    tree = et.parse(fic)
    root = tree.getroot()

    texts = tree.findall("//text/..")
    for x in texts:
        print(x)



def main():
    for filename in sys.argv[1:]:
        with file as open(filename
            internationalize_svg(file)

if __name__ == "__main__":
    main()

