#! /usr/bin/python3
"""
Annex program.
"""
import globbing

bashscript_pattern="""
#!/bin/bash

#Description: Résoud les homonymies associées à la suppression des parenthèses dans les labels des saisons de séries

"$(dirname "$0")/{filename} "$@"
"""

import re

import commands

cur_commands = commands.analyse_directory(".")
pwbscripts = commands.analyse_directory("pywikipedia/")

for filename in glob.glob("pywikipedia/*.py"):
	content = file(res).read()
	res = re.search("# *Description *:(.*)$", content)
	if res:
		command_name = filename
                if filename[-3:] ==".py":
                    command_name= filename[:-3]

                

